### ISSUE TITLE
Source config from package library

### ISSUE THREAD

**Issue by arthur-shaw** [arthur-shaw/ApproveReject#1]
## Problem

When the app is run, it fails to find `golem-config.yml` in the current working directory, looks for it in the golem package folder, and tries to copy it from that source to the (typically non-existent) `inst/` directory in the working directory. 

## Issue

After tinkering and looking at the golem source code, I think the problem is with how golem looks for golem-config.yml. See [here](https://github.com/ThinkR-open/golem/blob/master/R/config.R). This is probably well-suited for deployment where inst/golem-config.yml exists in the folder being deployed. But it’s not well-suited for running the application as a package on the desktop from any arbitrary folder.

## Current work-around

For the moment, I found a hack for making things work as I expect. However, I need to find a better way of accomplishing the same.

```r
library(ApproveReject)

# set the working directory to point to where the package is installed
# that is, to the R library folder
setwd(system.file(package = "ApproveReject"))

# run the app in that context
# so that golem-config.yml will be picked up from the root of the library dir
run_app()
```

**Comment by ColinFay** [comment]
Hey, 

Yeah so basically `golem::get_golem_name` & `golem::get_golem_version` are not working inside your package unless you specify where to look for. They try to be smart and create the file if it doesn't exist, hence the prompt you get here. 

To be fully transparent, these functions were meant to be more used during dev, for building wrappers around it. 

I confirm this is not documented and should not behave like this. 

One workaround I can see for now is via using desc, see my PR for a fix until this is fixed in golem. 

Nice app btw 👏

**Comment by arthur-shaw** [comment]
Wow. I did not expect a PR! This shows me what I should have done, and gives some helpful clarification on the intended scope of  `golem::get_golem_name` and `golem::get_golem_version`.

> Nice app btw 👏

Thanks for the undervedly kind words. What little I know about building Shiny apps, I learned--and continue to learn--from "Engineering Production-Grade Shiny Apps". Thanks for putting both `{golem}` and the book into the world.
